# -------------------------------------------------------------------
# Timing Constraints for LAB5 - RV32I/RV32IM CPU
# Base Clock: 50 MHz
# Period = 20 ns
# -------------------------------------------------------------------

# Main FPGA input clock: 50 MHz
create_clock -name {clk_i} -period 20.000 -waveform {0.000 10.000} [get_ports {clk_i}]

# Automatically constrain clocks generated by PLLs, if a PLL exists in the design
derive_pll_clocks

# Add clock uncertainty for setup/hold timing analysis
derive_clock_uncertainty